### ISSUE TITLE
Doctrine2

### ISSUE THREAD

**Issue by seyfer** [kenjis/php-orm-benchmark#1]
Please, add this ORM.

**Comment by TheCelavi** [comment]
:+1:

**Comment by garrettw** [comment]
:+1:

**Comment by kenjis** [comment]
[Removed]

The reason why _order by_ did not work was a mistake of EntityManager config (paths).

**Comment by kenjis** [comment]
Added: https://github.com/kenjis/php-orm-benchmark#results
