### ISSUE TITLE
Propel

### ISSUE THREAD

**Issue by clasense4** [kenjis/php-orm-benchmark#2]
Hi,

What about [propelorm](http://propelorm.org) ?

Thanks

**Comment by marcj** [comment]
+1 ;)

**Comment by Hadrien45** [comment]
:+1:

**Comment by ghost** [comment]
+1 :+1:

**Comment by motin** [comment]
+1!

**Comment by kenjis** [comment]
I have never used Propel. Pull Request is welcome.

**Comment by ghost** [comment]
@marcj Do you like to work on a PR?

**Comment by kenjis** [comment]
I merged PR: https://github.com/kenjis/php-orm-benchmark/blob/master/fuel/app/classes/controller/orm/propel2.php

Results: https://github.com/kenjis/php-orm-benchmark#results

If there is something wrong with the code, PR is welcome.
